name: CI

on:
  push:
  workflow_dispatch:
  
jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: auryc-build-master
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/auryc-inc/cache
          cache-to:   type=registry,ref=ghcr.io/auryc-inc/cache
          tags: |
            ghcr.io/${{ github.repository }}:${{env.GITHUB_SHA_SHORT}}
            ghcr.io/${{ github.repository }}:${{env.GITHUB_REF_NAME_SLUG}}
